{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% translate 'In case you’ve forgotten, you are:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
{% endautoescape %}NoReverseMatch at /account/reset_password/
Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
Request Method:	POST
Request URL:	http://localhost:8000/account/reset_password/
Django Version:	5.2.6
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'password_reset_done' not found. 'password_reset_done' is not a valid view function or pattern name.
Exception Location:	/Users/ahmednada/Desktop/iti_project-1/venv/lib/python3.13/site-packages/django/urls/resolvers.py, line 831, in _reverse_with_prefix
Raised during:	django.contrib.auth.views.PasswordResetView
Python Executable:	/Users/ahmednada/Desktop/iti_project-1/venv/bin/python3
Python Version:	3.13.0
Python Path:	
['/Users/ahmednada/Desktop/iti_project-1',
 '/Library/Frameworks/Python.framework/Versions/3.13/lib/python313.zip',
 '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13',
 '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload',
 '/Users/ahmednada/Desktop/iti_project-1/venv/lib/python3.13/site-packages']
Server time:	Sun, 14 Sep 2025 16:10:33 +0300
Traceback Switch to copy-and-paste view

/Users/ahmednada/Desktop/iti_project-1/venv/lib/python3.13/site-packages/django/core/handlers/exception.py, line 55, in inner
                response = get_response(request)
                               ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/Users/ahmednada/Desktop/iti_project-1/venv/lib/python3.13/site-packages/django/core/handlers/base.py, line 197, in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars